FROM myelinio/pyspark:spark-2.4.1

COPY requirements.txt requirements.txt
RUN pip install -r  requirements.txt


ENV GOOGLE_APPLICATION_CREDENTIALS /src/drift-detection/secrets/spark-sa.json
ENV PROJECT_ID myelin-development

ADD lib/gcs-connector-hadoop2-1.9.9-shaded.jar ${SPARK_HOME}/jars

ADD src/drift_detection_job.py /work
ADD ./src/pubsub.py /work
ADD ./src/skmultiflow_detector.py /work
ADD ./src/utils.py /work

ADD ./entrypoint.sh /opt/entrypoint.sh
